version: '3.7'

services:
  redis:
    image: redis:6.2.10-alpine
    command: redis-server --save "" --loglevel warning --requirepass redis123
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
