name: ci-cobuild.yml
on:
  #push:
  #  branches: ['main']
  #pull_request:
  #  branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: cobuild
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_id: [runner1, runner2, runner3]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Git config user
        run: |
          git config --local user.name "Rushbot"
          git config --local user.email "rushbot@users.noreply.github.com"

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Restore PNPM from GHA cache
        id: pnpm-cache-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.rush-pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}-v1003
          # If we can't find a match, restore the latest cache entry
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set RUSH_PNPM_STORE_PATH
        run: echo "RUSH_PNPM_STORE_PATH=~/.rush-pnpm-store" >> $GITHUB_ENV

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Save PNPM to GHA cache
        if: steps.pnpm-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.rush-pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}-v1003

      - name: Rush build (install-run-rush)
        run: node common/scripts/install-run-rush.js build --verbose --production --timeline
        env:
          # Prevent time-based browserslist update warning
          # See https://github.com/microsoft/rushstack/issues/2981
          BROWSERSLIST_IGNORE_OLD_DATA: 1
          RUSH_BUILD_CACHE_WRITE_ALLOWED: 1
          RUSH_BUILD_CACHE_CREDENTIAL: ${{ secrets.RUSH_BUILD_CACHE_CREDENTIAL }}
          RUSH_COBUILD_CONTEXT_ID: ${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}
          RUSH_COBUILD_RUNNER_ID: ${{ matrix.runner_id }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
