name: ci-single.yml
on:
  #push:
  #  branches: ['main']
  #pull_request:
  #  branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Git config user
        run: |
          git config --local user.name "Rushbot"
          git config --local user.email "rushbot@users.noreply.github.com"

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Read PNPM store from GHA cache
        uses: actions/cache@v3
        with:
          path: ~/.rush-pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}-v1000
          # If we can't find a match, restore the latest cache entry
          restore-keys: |
            ${{ runner.os }}-pnpm-
          # This step won't cause a write to the cache
          lookup-only: true

      - name: Set RUSH_PNPM_STORE_PATH
        run: echo "RUSH_PNPM_STORE_PATH=~/.rush-pnpm-store" >> $GITHUB_ENV

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Write PNPM store to GHA cache
        # (Only write if "rush install" succeeded)
        uses: actions/cache@v3
        with:
          path: ~/.rush-pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}-v1000

      - name: Rush build (install-run-rush)
        run: node common/scripts/install-run-rush.js build --verbose --production --timeline
        env:
          # Prevent time-based browserslist update warning
          # See https://github.com/microsoft/rushstack/issues/2981
          BROWSERSLIST_IGNORE_OLD_DATA: 1
          RUSH_BUILD_CACHE_WRITE_ALLOWED: 1
          RUSH_BUILD_CACHE_CREDENTIAL: ${{ secrets.RUSH_BUILD_CACHE_CREDENTIAL }}
